### ISSUE TITLE
[Webnode] Fork Googles jank app and add the webnode script to it for manual stress testing

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webnode#108]
https://github.com/GoogleChrome/devtools-samples/blob/master/jank/app.js

Clone repo, add our script, and then create a stop button to kill the treasure hunting. 

Now that you can:
- Add and remove blocks to simulate various client demands
- Optimize and Un-optimize clients code
- Start and Stop treasure hunting

**Comment by tenisakb** [comment]
PR: #148
