### ISSUE TITLE
[Webnode] Upgrade to Webpack 4

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webnode#119]
https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

There are huge performance gains with webpack 4
- Beware of loaders breaking, there was a syntax change with loaders.

**Comment by jfarago** [comment]
@tenisakb can you post some updates on this here in a comment?

**Comment by tenisakb** [comment]
Prereact was removed, @EdmundMai will push it in his pull request
