### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webnode#124]

**Comment by jfarago** [comment]
@tenisakb what unit tests would you like to focus this week?

**Comment by tenisakb** [comment]
Epics, Reducers, actions... some next changes
then we can continue with utils etc. but its not critical, I will have it really soon

**Comment by AaronVasquez** [comment]
What do we think about adding static types (typescript, flow, or reasonml)?

We can probably eliminate a lot of boilerplate if we add types to our actions and reducers. Most of the unit tests for those would be to just check the "plumbing" of actions are correct.

**Comment by tenisakb** [comment]
@AaronVasquez I have no experiences but reasonml looks fine.. we can try it :)
