### ISSUE TITLE
Webnode build is back up to almost 1MB

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webnode#125]
When I created my PR, I had the builds down to 687 MB. I dont know what happened but i just did a build and we are including the full libraries of node-forge and lodash again. 

We need to look at the import statements again and figure out why these libraries fully included, we are only using some of their methods

**Comment by jfarago** [comment]
Also remove redux logger

**Comment by AaronVasquez** [comment]
Can we remove lodash altogether?

**Comment by rfornea** [comment]
We could but we'd have to re-implement everything that lodash does for us.

**Comment by jfarago** [comment]
whoops

**Comment by EdmundMai** [comment]
i think it would be worth removing lodash. it looks like it's taking up a significant amount of space and it's only used in a few files

```➜  webnode git:(em-double-claim) ✗ ag "lodash" src
src/components/storage/index.js
5:import _ from "lodash";

src/redux/epics/treasure-hunt-epics.js
6:import _ from "lodash";

src/redux/reducers/node-reducer.test.js
1:import _ from "lodash";

src/redux/reducers/node-reducer.js
1:import _ from "lodash";

src/redux/services/iota.js
4:import _ from "lodash";

src/redux/selectors/node-selectors.js
2:import _ from "lodash";
➜  webnode git:(em-double-claim) ✗
```

**Comment by AaronVasquez** [comment]
Most of the stuff we use from lodash seem like thing we can do easily with vanilla JS, like `map` `find` `toArray`
I did a quick grep of lodash and found that we use it for this:

```shell
webnode/src/components/storage/index.js
5:import toArray from "lodash/toArray";

webnode/src/redux/epics/treasure-hunt-epics.js
6:import find from "lodash/find";

webnode/src/redux/reducers/node-reducer.test.js
1:import range from "lodash/range";
2:import map from "lodash/map";

webnode/src/redux/reducers/node-reducer.js
1:import range from "lodash/range";
2:import map from "lodash/map";

webnode/src/redux/services/iota.js
4:import findLastIndex from "lodash/findLastIndex";
5:import orderBy from "lodash/orderBy";

webnode/src/redux/selectors/node-selectors.js
2:import find from "lodash/find";
3:import includes from "lodash/includes";
```

**Comment by rfornea** [comment]
May as well remove it then.  We will have to remove it from datamap-generator as well.

**Comment by jfarago** [comment]
we are using even less of lodash in datamap-generator. Turns out, even when you import correctly, lodash overhead is still pretty large. Because of this, someone created a custom plugin to rebuild lodash... https://github.com/lodash/lodash-webpack-plugin

**Comment by AaronVasquez** [comment]
Speaking of datamap-generator, that's probably why the build size shot up again. Are we are importing the entire lodash lib in there?

**Comment by jfarago** [comment]
@AaronVasquez no, i refactored that last week
