### ISSUE TITLE
Port to node module

### ISSUE THREAD

**Issue by EdmundMai** [oysterprotocol/webnode#17]
- Remove react
- Copy and paste redux folder
- Add the node_modules that you need in the package.json file
- Call initWork() from index.js file

I already have a branch with a working redux setup, just work off that
https://github.com/oysterprotocol/webnode/compare/remove-react?expand=1

**Comment by tenisakb** [comment]
@AaronVasquez its done but not finally.... We will need to insert logic into the node module but ok.. I will close at the moment
