### ISSUE TITLE
Initialize a default set of neighbors

### ISSUE THREAD

**Issue by EdmundMai** [oysterprotocol/webnode#21]
From the whitepaper:

```
When a Web Node is either first introduced to the Oyster Network or has recently reset it's
identity, it has no Neighbors and must therefore build a list of Neighbors. The Web Node is
therefore faced with a Catch 22 dilemma. Neighbor identities are shared by other Web Nodes,
but it cannot ask because it doesn't known anyone initially. The initial solutions seems to be to
ask a Broker Node, but even Broker Node identities are shared via the Distributed Reputation
System that Web Nodes participate in. Therefore Web Nodes assume an initial trusted Broker
Node as a default reference. Website Owners are able to change their defaults to which ever
Broker Nodes they consider to be trustworthy, therefore maintaining the Network's compliance
with decentralization principles.
```

- On startup, generate a default set of Neighbors (distinguish between Broker Node neighbors and Web Node neighbors, potentially with separate sets)
- Persist the state in redux

**Comment by AaronVasquez** [comment]
@nymd do we have access to the AWS dashboard? How can we find the IPs of all our brokernodes?

**Comment by nymd** [comment]
A few ways to accomplish this.... 

Simplest: AWS lib

https://docs.aws.amazon.com/sdk-for-go/api/

I've used the python and bash libs extensively and they are good; I expect the Go one should be usable. First step would be to have a user created in AWS for this task, API keys created, then assigned a role allowing them to list EC2 instances. Second would be to tag the brokers in a meaningful way in the GUI. Then you'd be able to query AWS for live lists of brokers that only match a certain tag (type/version/etc).

More complex: discovery service like Consul

I don't think we need to go this route but you could have an external discovery service (example like Consul runs on the RAFT protocol to maintain consensus, requiring >3 master consul servers).  When brokers or other services come online, they register with Consul which then allows external services to get IPs of server groups or types of services.

**Comment by nymd** [comment]
https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/ec2-example-manage-instances.html

**Comment by AaronVasquez** [comment]
@EdmundMai @rfornea 

Sounds like from the whitepaper that the website owner would be able choose the brokernode IP. I'm assuming this would mean passing in ENV variables to the script.

For v1 should we have just a static list of default neighbors? Or is there a requirement to dynamically choose neighbors?

The default list of neighbors would also be the fallback in case the IPs passed in by the website owner is invalid.

**Comment by EdmundMai** [comment]
V1 should be static

**Comment by rfornea** [comment]
I think static is fine.  And I think using the default as a fallback would be a good idea too.  

They could do ENV variables, but I think it could also be an attribute on the script tag.

**Comment by AaronVasquez** [comment]
Attributes on the script tag SGTM. 

@EdmundMai @tenisakb Is there a way to pass in the list of IPs if the website owner stalls with NPM as a package?

**Comment by EdmundMai** [comment]
If it's through NPM they'll have acccess to an object. When we do the NPM version we'll allow them to pass params: `OysterWebnode.init(ipAddresses = [])` so they can do `OysterWebnode.init(["1.2.3", ...])`

**Comment by AaronVasquez** [comment]
@automyr do we know the static list of IPs already? or are we still getting that set up?

**Comment by automyr** [comment]
Haven't set up the final instances yet, will do so next week. I want to solve some issues with uploads first using smaller instances.

**Comment by AaronVasquez** [comment]
Ok, whenever it's ready, can you paste the list of IPs here?

**Comment by AaronVasquez** [comment]
@automyr any update on the IPs?
