### ISSUE TITLE
[Webnode] Claim Treasure

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/webnode#34]
There will be a new endpoint on the broker:
`POST /api/v1/treasures`
```js
// POST body
{
    receiverEthAddr: "0xThisIsTheWebsiteOwnersAddr"
    treasure: {
        genesisHash: "genesisHash",
        sectorIdx: 123,
        ethAddr: "ethAddr",
        ethKey: "0xSuperSecretKey",
    }
}
```

1. The website owner needs to provide an ETH address when starting the script. Any treasure found will be transferred there.
2. When making the POST call, attach a listener for the `Claim` event.
    1. Create a `/services/ethereum.js` file.
        1. Install and import `web3.js`
        2. Create a function `subsribeToClaim` which listens for the `Claim` event (https://github.com/oysterprotocol/smartcontract/blob/master/OysterPearl.sol#L40)
    2. Create a `epics/treasures.js` file.
        1. Create a function `claimTreasureEpic` and add this to the epics middleware.
            1. Perform POST (as listed above ^) to broker to claim treasure
            2. In the same epic, subscribe to the `Claim` event. For now, we can just console.log when the event is triggered since we haven't decided what to do at that point.

**Comment by tenisakb** [comment]
@rfornea 
So I am changing to:

// POST body
{
    receiverEthAddr: "0xThisIsTheWebsiteOwnersAddr"
    treasure: {
        genesisHash: "genesisHash",
        sectorIdx: 123,
        ethAddr: "ethAddr",
        ethKey: "0xSuperSecretKey",
        fileSize: 500000,
    }
}

**Comment by rfornea** [comment]
Depends on if we want numChunks or fileSize.  The corresponding brokernode issue for this change expects numChunks.  

If we ever change our encryption/decryption method for file chunks, this distinction matters.

**Comment by tenisakb** [comment]
Ok, always we are using numChunks so I will use numChanks :-))
