### ISSUE TITLE
Consider adding prefix to attribute

### ISSUE THREAD

**Issue by Malvoz** [oysterprotocol/webnode#36]
The current preview of the Oyster script uses the custom attribute `payout`, this might cause issues in the future if the web platform extends to such an attribute. Even if it never will use that exact name for an attribute it might cause errors in HTML validation for web authors.

Consider adding a prefix, such as `data-payout` or `data-payout-address`. There is [currently a discussion](https://github.com/w3c/html/issues/1337) on the restrictions for custom attributes on the W3C and WHATWG.

**Comment by AaronVasquez** [comment]
@EdmundMai This sounds like a simple change to `webnode`
