### ISSUE TITLE
[Webnode] Add flag to prevent webnode script from running and add a message to the screen so the user can opt out of the oyster script.

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/webnode#44]
The users of the websites that run Oyster shouldn't have to allow the webnode script to run if they don't want to.  When the page first loads, we should open a consent box to allow the user to allow the webnode script or not.  If they choose not to allow the script, we should set a flag so that it won't run.  

Attached are some sample images of what it should look like.

**Comment by rfornea** [comment]
![consent draft desktop](https://user-images.githubusercontent.com/17357002/39641718-3d6d35e4-4f9d-11e8-9cbe-cdd8f5e767e6.png)
![consent draft mobile](https://user-images.githubusercontent.com/17357002/39641730-47e78fc4-4f9d-11e8-9536-47ad70019c28.png)

**Comment by rfornea** [comment]
@tfrench93 If you have any other images feel free to post them in this github issue.

**Comment by rfornea** [comment]
Thanks!  Hope you are doing well.  :)

**Comment by pandora23** [comment]
I am doing rather well.  Been down in Portland for a month.  I live with
seven people in this huge house, and have been spending most of my time
clearing out blackberry bushes and setting up a garden - though I spend a
bit of time on bitcointalk and am learning Golang though Rust is calling my
name.

I guess this is a bad place to communicate, just thought I would send some
good energies as I am liking what I am seeing in terms of progress - you
guys were facing the next set of difficult design tasks with the PRL
burying and nuances.   Anyways,  I will stop by and visit everyone on Slack
later this week!

**Comment by rfornea** [comment]
@pandora23 @EdmundMai  This is something that will be good for Ali K to work on.  Do we want to keep React to display this dialogue box?

**Comment by Alisamix** [comment]
_Early draft specs:_

**Desktop:** 

left-side logo text: 18, semi-bold, Poppins, 

Middle Title: 9, semi-bold, Poppins 

Middle Body: 9, regular (semi-bold for Learn More…), Open Sans, 

Buttons: 13, semi-bold, Poppins 

**Mobile:** 

Title:12, semi-bold, Poppins 

Body: 11, Regular (except for ‘Learn mode…’), Open Sans,

Buttons: 11, semi-bold, Poppins
