### ISSUE TITLE
[webnode] Running build script fails to compile

### ISSUE THREAD

**Issue by Alisamix** [oysterprotocol/webnode#45]
Trying to run "npm run-script build" throws this error:

`Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:
     ./node_modules/curl.lib.js/src/constants.js:10`

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Options we have:**

_To resolve this:_
- Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.
Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

- Fork the package and publish a corrected version yourself.

- If the dependency is small enough, copy it to your src/ folder and treat it as application code.

**Comment by jfarago** [comment]
This has been resovled
