### ISSUE TITLE
[Webnode] genesisHash is null

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/webnode#71]
Steps to reproduce:  
-Pull down code from my latest PR (#70), unless it's in master already, in which case pull down master
-In config/index.js, hardcode in a working broker for API_ROOT_URL
-Input a genesis hash with a treasure in it and number of chunks 
-Pop open the "Network" tab and notice that in the requests to the broker, genesisHash is null, and ethKey is sometimes null, but sometimes not.  

![image.png](https://images.zenhubusercontent.com/5a8c55194b5806bc2bc7ac81/89c2f884-e76f-44cf-8255-f52c606c0811)

**Comment by AaronVasquez** [comment]
Can we close this issue? or is it still happening?

**Comment by rfornea** [comment]
I am not sure.  @EdmundMai @jfarago

**Comment by EdmundMai** [comment]
Should be fixed
