### ISSUE TITLE
[Webnode] IOTA Transaction is undefined when searching for treasure

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webnode#75]
Steps to reproduce:

1. Look for treasure.
2. See an error "TypeError: Cannot read property 'signatureMessageFragment' of undefined"

I have used the same genesis hash several times before and have not had an issue until today. Now, i get the error that you see below. @rfornea said she does not think its a treasure issue and possibly a race condition.                       

gensisHash: e16f77bcdb3b67362a7ad301e29fc674884e6b6aa73d44a405880fb77bec9bdf

![image.png](https://images.zenhubusercontent.com/5acd4eef4b5806bc2bce9075/10307b84-3dc9-441c-9e6e-f766188d28d1)

**Comment by automyr** [comment]
Perhaps this is for another reason, but is this a recent upload with new treasure? 

Because we switched to a new private tangle (to update IRI to 1.4.2.4) so all previous files are gone. If it's trying to use a transaction that's no longer there, it could result in this issue.

**Comment by rfornea** [comment]
@jfarago What brokers were you pointing to again? Yours or mine?

**Comment by jfarago** [comment]
I am pointing to my brokers. I had been working with that hash all day and all of a sudden that is the response i started getting. This is not a recent upload, let me try that and see what happens.

**Comment by jfarago** [comment]
No longer seeing this issue
