### ISSUE TITLE
[Webnode] Production build fails to compile

### ISSUE THREAD

**Issue by jfarago** [oysterprotocol/webnode#79]
**Steps to reproduce**

1. Run `npm run build`

**Expected Output**

![image.png](https://images.zenhubusercontent.com/5acd4eef4b5806bc2bce9075/65d4f13e-a9a8-46b0-a220-5293ff1bade1)

**Tips to resolve**

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

React says that the error is likely due to the library not being compiled to ES5 but I checked and the file its failing on is in ES5

https://github.com/iotaledger/curl.lib.js/blob/master/src/constants.js

**Comment by AaronVasquez** [comment]
This could be why it's not compiled: https://github.com/iotaledger/curl.lib.js/issues/14

We might need to contribute a PR to fix their build. Look like they are using Gulp, so this might be helpful:
http://www.codeblocq.com/2016/03/Setup-Gulp-to-compile-ES6-ES2015-code/

**Comment by jfarago** [comment]
We  no longer need a production build for the webnode, we have a separate build than our test environment
