### ISSUE TITLE
Size concerns

### ISSUE THREAD

**Issue by aleclarson** [oysterprotocol/webnode#94]
I noticed [webnode.min.js][1] is almost 1mb in size. That's *a lot* of Javascript to parse, but I guess developers could load it *after* the first meaningful paint (instead of before as Oyster's website suggests).

I'm in favor of a webnode package on NPM that only has the bare essentials. Any extras (like components dependent on React) should be packaged separately under Oyster's NPM handle. This strategy allows more advanced developers to use their preferred bundler to deduplicate code and remove dead code. Does the team have plans for this approach?

Cheers! 😄 

[1]: https://github.com/oysterprotocol/webnode/blob/0a743e1/webnode/build/static/js/oyster-webnode-0.0.1.min.js

**Comment by davidgilbertson** [comment]
FWIW looks like it's only 463 KB gzipped.

But still, that's probably five seconds of download and parse time on a phone.

**Comment by jfarago** [comment]
@aleclarson this is a valid concern and something we are looking into. We recently ejected form react-scripts to control the webpack build and add a worker-loader. Yesterday, I created several tasks to clean up and optimize the build process. 

The issues are [104](https://github.com/oysterprotocol/webnode/issues/104) and [107](https://github.com/oysterprotocol/webnode/issues/107)

**Comment by jfarago** [comment]
We are going to continue to track this with build optimizations epic and try to reduce the package as much as we can. We have already started to eliminate 3rd party dependencies
